### PR TITLE
finished level barrier

### PR DESCRIPTION
**Pull request by ghost**
hi

### CODE REVIEW

**Review by Catafrancia123 — CHANGES_REQUESTED** [review]
On saveloader, i have implemented the os_edit on my end. You dont need save.json here (since its automatically made). You dont need some spacing on operations/commas e.g.(1 - 1) just use (1-1). Use booleans bruh💀 and why did you make oses.json horrid??

**Review by markverb1 — APPROVED** [review]
don't know what this changes but the code looks fine

**Comment by ghost** [comment]
fixed

**Review by Catafrancia123 — APPROVED** [review]
Good work my friend, Ill merge this and maybe optimize a bit of your code.

**Pull request merged**
